version: '2'
services:
  nginx:
    build: .
    container_name: blog-nginx
    environment:
      VIRTUAL_HOST: to-hutohu.com
      LETSENCRYPT_HOST: to-hutohu.com
      LETSENCRYPT_EMAIL: tohu.soy@gmail.com
    restart: always
networks:
  default:
    external:
      name: docker-nginx_default
